## Bygger APK som appen hämtar för automatisk uopdatering.
name: Build and Release APK

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch (adjust if you use another branch)
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Use Java 17 for Android Gradle plugin 8.7.0
          distribution: 'temurin'

      - name: Build the APK
        run: ./gradlew assembleRelease  # Build APK with Gradle

      - name: Upload APK to GitHub releases
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release.apk  # Path to your built APK
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for creating the release
