## Bygger APK som appen hämtar för automatisk uopdatering.
name: Build and Release APK

on:
  push:
    branches:
      - main  # Kör när kod pushas till main (ändra om du har en annan branch)
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'  # Lägg till denna rad

      - name: Build the APK
        run: ./gradlew assembleRelease  # Kör gradle kommando för att bygga APK

      - name: Upload APK to GitHub releases
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release.apk  # Sökvägen till din byggda APK
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Använd GitHub token för att skapa release
