name: Generate Keystore

on: workflow_dispatch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore and base64 encode
        run: |
          keytool -genkeypair \
            -alias publikiosk-key \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass password123 \
            -keypass keypass123 \
            -dname "CN=Auto, OU=GitHub, O=Automation, L=Stockholm, S=Stockholm, C=SE" \
            -keystore release.keystore

          base64 release.keystore | tr -d '\n' > release.keystore.b64
          echo "👇 Copy this and add it as a GitHub secret:"
          cat release.keystore.b64
